// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sazkomat.Data.Data;

#nullable disable

namespace Sazkomat.Data.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20251023211010_AddMatchEntity")]
    partial class AddMatchEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sazkomat.Data.Entities.ImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IncludeWithoutOdds")
                        .HasColumnType("boolean")
                        .HasColumnName("include_without_odds");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<string>("Progress")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("progress");

                    b.Property<string>("Seasons")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("seasons");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.HasIndex("Status");

                    b.ToTable("import_jobs", "data_import");
                });

            modelBuilder.Entity("Sazkomat.Data.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AwayOdds")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("away_odds");

                    b.Property<int>("AwayScore")
                        .HasColumnType("integer")
                        .HasColumnName("away_score");

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("away_team");

                    b.Property<string>("BetExplorerUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("betexplorer_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DrawOdds")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("draw_odds");

                    b.Property<decimal?>("HomeOdds")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("home_odds");

                    b.Property<int>("HomeScore")
                        .HasColumnType("integer")
                        .HasColumnName("home_score");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("home_team");

                    b.Property<DateTime?>("MatchDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("match_date");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("result");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid")
                        .HasColumnName("round_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MatchDate");

                    b.HasIndex("Result");

                    b.HasIndex("RoundId");

                    b.HasIndex("HomeTeam", "AwayTeam");

                    b.ToTable("matches", "data_import");
                });

            modelBuilder.Entity("Sazkomat.Data.Entities.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AwayWins")
                        .HasColumnType("integer")
                        .HasColumnName("away_wins");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CumulativeOddsAway")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("cumulative_odds_away");

                    b.Property<decimal>("CumulativeOddsDraw")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("cumulative_odds_draw");

                    b.Property<decimal>("CumulativeOddsHome")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("cumulative_odds_home");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("data_source");

                    b.Property<int>("Draws")
                        .HasColumnType("integer")
                        .HasColumnName("draws");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<int>("HomeWins")
                        .HasColumnType("integer")
                        .HasColumnName("home_wins");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid")
                        .HasColumnName("league_id");

                    b.Property<int>("MatchesCount")
                        .HasColumnType("integer")
                        .HasColumnName("matches_count");

                    b.Property<string>("OddsComplete")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("odds_complete");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer")
                        .HasColumnName("round_number");

                    b.Property<DateTime>("ScrapedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scraped_at");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("season");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("SummaryResult")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("summary_result");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ScrapedAt");

                    b.HasIndex("Season");

                    b.HasIndex("LeagueId", "Season");

                    b.HasIndex("LeagueId", "Season", "RoundNumber")
                        .IsUnique();

                    b.ToTable("rounds", "data_import");
                });

            modelBuilder.Entity("Sazkomat.Data.Entities.Match", b =>
                {
                    b.HasOne("Sazkomat.Data.Entities.Round", "Round")
                        .WithMany("Matches")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("Sazkomat.Data.Entities.Round", b =>
                {
                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
