// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sazkomat.Data.Data;

#nullable disable

namespace Sazkomat.Data.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20251212180000_AddUnmatchedLeagues")]
    partial class AddUnmatchedLeagues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // This is just a placeholder - the actual model is defined in the ModelSnapshot
            // EF will use this to track the migration
#pragma warning restore 612, 618
        }
    }
}
