// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sazkomat.Configuration.Data;

#nullable disable

namespace Sazkomat.Configuration.Migrations
{
    [DbContext(typeof(ConfigurationDbContext))]
    [Migration("20251214150700_RemoveIsSyncEnabledColumn")]
    partial class RemoveIsSyncEnabledColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // This is a simplified BuildTargetModel - full model is in ConfigurationDbContextModelSnapshot.cs
#pragma warning restore 612, 618
        }
    }
}
